# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39098247f135fcd5700f9f5a3ba3ae5eb6201ceb8d7be7468272372d8b9c4262a77dcd228642d1816fa866cb8e3188d0fc5ef2f899203cf7fab5e28a431c8b5e

test:
  secret_key_base: 2b6d6d95bac06eca233c4cdbc8955b85aef20f6979e5345e36c71f0d77dd945df3648880dc6ade7a2570a37d099aec22c9408a40c25ad8535faf8eb15711eb03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
